language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install
- pipenv install --dev
- pipenv install -e .
script:
- pipenv run python -m pytest --cov=nougat_router tests
- pipenv run codecov
deploy:
  provider: pypi
  user: kilerd
  distributions: bdist_wheel
  password:
    secure: YIkJ3LcgeAhh51UagFVp8dDBSWzOyUb3bcItLIPkYd82Cmmsm/tMCKHz7rJk+ZNuM4ZVfq9oX7o1ivILCRfJB6zmzhiKR08d7wgvq7EV/AJ6WsGJsZOLUhH3VrVcZj+Z3uLrJzML55kp5NGY6OqzOvXpjhXua/zLZNBC503h4m98+AfzwHWNhwuD8LU24H5OlqexrWe+ibS+YVBYd9xvpqEcQVyyb9223pO4SiXOcj0BcBo/7huLcL4yrICvDiDlblMj9baV6a9IKbA9RrV+LsKu1mNTLSi1ObT5G3Kw1ddL7XoFH0FjlPW9mlG5cpla8jLcCpTl8OJTTKGy0vUuRbR2zfi+XySL5QOj1EEJINX/TzSiSNDfon6R3l/qCwiL7EjA590sdpyaFArHmyXUEnZh8IcC49ewTck+Ggl4u767N3b49VG88vGvTp5GgWMBa6i5bb4SmSvMBHOIKeKE5kmAA5mAtHzBtuxMHWABCU4Wy5P0OLvhA8cgwt+DsE//zsX66pVRBPO8AvU+mK9KHkaQfHov45+nD41l9T2euKyNm1/qVP20odcfAZQE98Rmu1fYn4vj/PZJffKlossLETZv4TL9JKr8Qi80JkqfiWSxSpz7FSOgKOOMOYdor6Cr0XFnL7xUCeINpLu3MNHafrgjSmYb360cvkMoFHs0x/U=
  on:
    tags: true